# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


#logo: site-logo.svg
#search: false

title: rotty3000.doublebite.com
logo: "/assets/images/site-logo.svg"
name: rotty3000.doublebite.com
email: rotty3000@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My personal thoughts.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rotty3000.doublebite.com" # the base hostname & protocol for your site, e.g. http://example.com
repository: "rotty3000/rotty3000.github.io"
twitter_username: rotty3000
github_username:  rotty3000

permalink:   /:categories/:title/
breadcrumbs: true

# Build settings
#theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.22.0"
minimal_mistakes_skin: "contrast" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

twitter:
  username: "rotty3000"

# Site owner
author:
  name: Raymond Augé
  avatar: "/assets/images/bio-photo.jpg"
  bio: "My personal thoughts."
  #email: rotty3000@gmail.com
  location: "Ontario, Canada"
  twitter: rotty3000
  github: rotty3000

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      layout: single
      author_profile: true
      read_time: true
      share: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      author_profile: true
