apiVersion: v1
kind: Pod
metadata:
  name: application
spec:
  containers:
  - name: application
    image: nginx
    env:
    - name: DB_HOST
      value: database
    - name: DB_PORT
      value: "5432"
    envFrom:
    - secretRef:
        name: db-secret