apiVersion: v1
kind: Pod
metadata:
  name: application
  annotations:
    k8s.ksgate.org/db-pod: |
      {
        "kind": "Pod",
        "name": "database",
        "expression": "resource.status.phase == 'Running'"
      }
    k8s.ksgate.org/db-secret: |
      {
        "kind": "Secret",
        "name": "db-secret"
      }
spec:
  containers:
  - name: application
    image: nginx
    env:
    - name: DB_HOST
      value: database
    - name: DB_PORT
      value: "5432"
    envFrom:
    - secretRef:
        name: db-secret
  schedulingGates:
  - name: k8s.ksgate.org/database
  - name: k8s.ksgate.org/db-secret