apiVersion: v1
kind: Pod
metadata:
  name: database
  annotations:
    k8s.ksgate.org/db-secret: |
      {
        "kind": "Secret",
        "name": "db-secret"
      }
spec:
  containers:
  - name: database
    image: postgres
    envFrom:
    - secretRef:
        name: db-secret
  schedulingGates:
  - name: k8s.ksgate.org/db-secret