apiVersion: v1
kind: Pod
metadata:
  name: application
  annotations:
    my.scheduling.gate/db-secret: "...condition..."
    my.scheduling.gate/database: "...condition..."
spec:
  containers:
  - name: application
    image: nginx
    env:
    - name: DB_HOST
      value: database
    - name: DB_PORT
      value: "5432"
    envFrom:
    - secretRef:
        name: db-secret
  schedulingGates:
  - name: my.scheduling.gate/db-secret
  - name: my.scheduling.gate/database