apiVersion: v1
kind: Pod
metadata:
  name: application
spec:
  initContainers:
  - name: wait-for-database
    image: busybox
    command: ["sh", "-c", "until nc -z database 5432; do echo waiting for database; sleep 1; done"]
  containers:
  - name: application
    image: nginx
    env:
    - name: DB_HOST
      value: database
    - name: DB_PORT
      value: "5432"
    envFrom:
    - secretRef:
        name: db-secret